services:
  server:
    image: nastea13/auth-server:latest
    build:
      context: .
    environment:
      NODE_ENV: development
      # Adaugă aici URL-ul bazei de date ca să se poată conecta la serviciul 'db' de mai jos
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
